### ISSUE TITLE
Multimedia Icon

### ISSUE THREAD

**Issue by hernandito** [ground7/unraid-animated-svgs#17]
I created this icon... What do you think? Unsure how it would work with your colors... I think it should be a simple re-color.

[multimedia.zip](https://github.com/ground7/unraid-animated-svgs/files/4723277/multimedia.zip)

**Comment by ground7** [comment]
Ah, I do remember this, though I didn't get what the top part was in the version you sent me since it didn't have the rectangle. Also I believe the name was something like mm, which I didn't realize meant multimedia. I think this is not bad, but it makes me think of music or music videos. You had one on the forum like this: 
![image](https://user-images.githubusercontent.com/19885992/83688852-df6d7900-a5a2-11ea-8667-c693e5e33867.png)
Did you discard it? I think it probably works better for the category.

**Comment by hernandito** [comment]
Hi.

I had completely forgotten about this one. I came up with a good idea... In addition to the play arrow, I added a musical note in the center. What if the arrow and musical note morph/toggle/fade/blink back and forth. The slider should also move.

![Image 8](https://user-images.githubusercontent.com/787317/83773437-80ffd380-a652-11ea-86da-0d372a3bc550.png)

[video.zip](https://github.com/ground7/unraid-animated-svgs/files/4730838/video.zip)

**Comment by ground7** [comment]
Added in 0507e7d2b54cf40aa7f2db39462fcf1da10790e5 and db11435dfece3b099c5701cd7fcfcdbb3b36ad25
